Issue 17 edit profile
dci-python-backend-assignments/tdd-class-social pull request #31
Opened 2022-07-06 12:30 UTC by Hans-Lambda

2022-07-06 13:00 UTC, mathiasbrito-dci requested changes

2022-07-06 13:00 UTC, mathiasbrito-dci commented on class_social/users.py
> +@users_routes.patch('/users/edit_user_profile')
What about `patch` in `/users/{user_id}/profile`, do you think you can change that until the end of the class?

2022-07-11 14:33 UTC, mathiasbrito-dci approved these changes
Ok, all tests, including from others are passing after testing merged to the main...

2022-07-11 14:33 UTC, merged

2022-07-11 18:09 UTC, Hans-Lambda commented
> Ok, all tests, including from others are passing after testing merged to the main...

Nice that it worked out